doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            educational_process_plan_forma: 'App\Model\EducationalProcess\Entity\EducationalPlan\FormEducationType'
            educational_process_plan_status: 'App\Model\EducationalProcess\Entity\EducationalPlan\StatusType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            # App:
            #     is_bundle: false
            #     type: annotation
            #     dir: '%kernel.project_dir%/src/Entity'
            #     prefix: 'App\Entity'
            #     alias: App
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            EducationalProcess:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/EducationalProcess/Entity'
                prefix: 'App\Model\EducationalProcess\Entity'
                alias: EducationalProcess
