parameters:
    # Здесь могут быть параметры бандла
    
services:
    # Конфигурация по умолчанию (только для этого файла)
    _defaults:
        # Включает механизм автоматической подстановки зависимостей контейнера в ваши сервисы
        autowire: true
        # Включает механизм автоконфигурации
        autoconfigure: true

    kudin\EducationGraphBundle\Controller\EditorController: ~
